quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=ecommerce_user
quarkus.datasource.password=1234
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/ecommerce_db

quarkus.hibernate-orm.schema-management.strategy = update
quarkus.hibernate-orm.log.sql=true
quarkus.scheduler.enabled=true
quarkus.log.level=INFO
quarkus.http.port=9090

quarkus.oidc.auth-server-url=http://localhost:8080/realms/ecommerce
quarkus.oidc.client-id=ecommerce-client
quarkus.oidc.credentials.secret=0kCZeCPJUI6Lfk8BWe9l1cUCPuhkccGl
quarkus.oidc.application-type=service
quarkus.oidc.roles.source=accesstoken