quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=ecommerce_user
quarkus.datasource.password=1234
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/ecommerce_db

quarkus.hibernate-orm.schema-management.strategy = update
quarkus.hibernate-orm.log.sql=true